name: Test many job

on:
  workflow_dispatch:
    inputs:
      flag:
        required: true
        default: "1"

jobs:
  check-pr:
    runs-on: ubuntu-latest
    outputs:
      pr-number: ${{ steps.check-prs.outputs.PR_NUMBER }}
    steps:
      - name: Check PRs
        id: check-prs
        run: |
          echo "PR_NUMBER=${{ github.event.inputs.flag }}" >> $GITHUB_OUTPUT

  publish:
    needs: [check-pr]
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: |
          echo ${{ needs.check-pr.outputs.pr-number }}
