name: Conditional Workflow Example

on:
  workflow_dispatch:
    inputs:
      mode:
        description: 'Chế độ chạy (1 hoặc 2)'
        required: true
        default: '1'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Chạy job1
        run: echo "Đây là job1"

  job2:
    if: ${{ github.event.inputs.mode == '1' }}
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Chạy job2
        run: echo "Đây là job2 (chạy khi mode == 1)"

  job3:
    runs-on: ubuntu-latest
    needs: |
      ${{ github.event.inputs.mode == '1' && 'job2' || 'job1' }}
    if: >
      (github.event.inputs.mode == '1' && success() && needs.job2.result == 'success') ||
      (github.event.inputs.mode == '2' && success() && needs.job1.result == 'success')
    steps:
      - name: Chạy job3
        run: echo "Đây là job3 (tùy thuộc vào mode và job thành công)"
