name: Global ENV User Info Workflow

on:
  workflow_dispatch:
    inputs:
      userId:
        description: 'User ID'
        required: true
        default: 'user1'

env:
  USER_DATA: >
    {
      "user1": {"name": "Alice", "age": 30, "sex": "Female"},
      "user2": {"name": "Bob", "age": 25, "sex": "Male"},
      "user3": {"name": "Charlie", "age": 40, "sex": "Non-binary"}
    }

jobs:
  get-user-info:
    runs-on: ubuntu-latest
    steps:
      - name: Extract user info from global env
        id: extract
        run: |
          USER_ID="${{ github.event.inputs.userId }}"
          DATA='${{ env.USER_DATA }}'

          # Kiểm tra user
          if ! echo "$DATA" | jq -e --arg id "$USER_ID" 'has($id)' > /dev/null; then
            echo "User ID '$USER_ID' not found."
            exit 1
          fi

          NAME=$(echo "$DATA" | jq -r --arg id "$USER_ID" '.[$id].name')
          AGE=$(echo "$DATA" | jq -r --arg id "$USER_ID" '.[$id].age')
          SEX=$(echo "$DATA" | jq -r --arg id "$USER_ID" '.[$id].sex')

          echo "name=$NAME" >> $GITHUB_OUTPUT
          echo "age=$AGE" >> $GITHUB_OUTPUT
          echo "sex=$SEX" >> $GITHUB_OUTPUT

      - name: Show user info
        run: |
          echo "Name: ${{ steps.extract.outputs.name }}"
          echo "Age: ${{ steps.extract.outputs.age }}"
          echo "Sex: ${{ steps.extract.outputs.sex }}"userId }}"_
