name: Test many job

on:
  workflow_dispatch:
    inputs:
      flag:
        required: true
        default: "1"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: |
          echo 1.success

  test:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: test
        run: |
          if [[ ${{ github.event.inputs.flag }} ==  '1' ]]; then
            echo 2.success
            exit 0
          else
            echo 2.failed
            exit 1
          fi
          

  summary:
    runs-on: ubuntu-latest
    needs: [deploy, test]
    steps:
      - name: Summary
        run: |
          echo 3.success
