name: Conditional Workflow

on:
  workflow_dispatch:
    inputs:
      mode:
        description: 'Chọn chế độ chạy (1 hoặc 2)'
        required: true
        default: '1'

jobs:
  job1:
    if: ${{ inputs.mode == '1' || inputs.mode == '2' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Đang chạy job1"

  job2:
    if: ${{ github.event.inputs.mode == '1' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Đang chạy job2"
          exit 1


  job3:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    if: ${{ (github.event.inputs.mode == '1' && needs.job2.result == 'success') || (github.event.inputs.mode == '2' && needs.job1.result == 'success') }}
    steps:
      - run: echo "Đang chạy job3"
